"""Study 2 trial construction with EXACT position counterbalancing (D-28).

Vocabulary:

  semantic X / Y   fixed identity of the two alternatives. X is always
                   `option_a` from configs/preferences.yaml, Y always `option_b`.
                   Scores are expressed with respect to X.
  x_position       "x_first" -> X rendered as displayed A; "x_second" -> X as B.

The semantic identity never changes when the display order does. Only
`displayed_to_semantic` maps a returned letter back to X/Y, and nothing else in
Study 2 may do that mapping.
"""

from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass, field
from typing import Any

X_FIRST = "x_first"
X_SECOND = "x_second"
POSITIONS = (X_FIRST, X_SECOND)


@dataclass
class FollowupTrial:
    trial_id: str
    study_id: str
    experiment_id: str
    model_key: str
    preference_id: str
    preference_category: str
    is_control: bool
    semantic_x: str
    semantic_y: str
    displayed_A: str
    displayed_B: str
    semantic_x_position: str      # "x_first" | "x_second"
    repetition_index: int
    prompt: str
    messages: list[dict] = field(default_factory=list)

    def as_record(self) -> dict:
        return asdict(self)


def displayed_to_semantic(choice_displayed: str | None, x_position: str) -> str | None:
    """Map the letter the model returned back to semantic 'X' or 'Y'.

    The single place in Study 2 where display order is undone.
    """
    if choice_displayed not in ("A", "B"):
        return None
    if x_position == X_FIRST:          # X was shown as A
        return "X" if choice_displayed == "A" else "Y"
    return "Y" if choice_displayed == "A" else "X"


def _tid(*parts: object) -> str:
    return "|".join(str(p) for p in parts)


def build_trials(item, model_key: str, reps_per_position: int, study_id: str,
                 experiment_id: str, system_prompt: str, user_template: str,
                 is_control: bool = False) -> list[FollowupTrial]:
    """Exactly `reps_per_position` trials in EACH position, for one (item, model).

    Balance is structural: the two positions are generated by the same loop, so
    an unequal split is impossible by construction rather than in expectation.
    """
    trials: list[FollowupTrial] = []
    for position in POSITIONS:
        for rep in range(reps_per_position):
            if position == X_FIRST:
                shown_a, shown_b = item.option_a, item.option_b
            else:
                shown_a, shown_b = item.option_b, item.option_a
            prompt = user_template.format(shown_a=shown_a, shown_b=shown_b)
            trials.append(FollowupTrial(
                trial_id=_tid(experiment_id, model_key, item.id, position, f"r{rep}"),
                study_id=study_id,
                experiment_id=experiment_id,
                model_key=model_key,
                preference_id=item.id,
                preference_category=item.category,
                is_control=is_control,
                semantic_x=item.option_a,
                semantic_y=item.option_b,
                displayed_A=shown_a,
                displayed_B=shown_b,
                semantic_x_position=position,
                repetition_index=rep,
                prompt=prompt,
                messages=[{"role": "system", "content": system_prompt},
                          {"role": "user", "content": prompt}],
            ))
    return trials


def verify_counterbalance(trials: list[FollowupTrial]) -> dict:
    """Assert exact balance per (model, item). Returns a report; never silently passes."""
    counts: dict[tuple, dict[str, int]] = {}
    for t in trials:
        c = counts.setdefault((t.model_key, t.preference_id), {X_FIRST: 0, X_SECOND: 0})
        c[t.semantic_x_position] += 1
    bad = {k: v for k, v in counts.items() if v[X_FIRST] != v[X_SECOND]}
    return {
        "balanced": not bad,
        "n_cells": len(counts),
        "unbalanced_cells": {f"{k[0]}/{k[1]}": v for k, v in bad.items()},
    }


def budget(trials: list[FollowupTrial], max_tokens: int) -> dict:
    by_model: dict[str, int] = {}
    for t in trials:
        by_model[t.model_key] = by_model.get(t.model_key, 0) + 1
    n = len(trials)
    approx_prompt = sum(len(t.prompt) for t in trials) / 4.0  # ~4 chars/token
    return {
        "total_calls": n,
        "calls_by_model": by_model,
        "approx_prompt_tokens": int(approx_prompt),
        "max_completion_tokens": n * max_tokens,
    }
