"""EXPLORATORY: cross-method convergence before vs after removing position.

    python -m src.position_adjusted

Study 1 showed that some raw method scores carry large display-position effects.
This asks the natural follow-up: **if position is removed from the measurement,
do the convergence conclusions change?**

The adjusted score averages the two display-order conditions, in semantic
coordinates, so a symmetric position effect cancels:

    s_adjusted = ( E[s | semantic A shown first] + E[s | semantic A shown second] ) / 2

For the pairwise method this is algebraically identical to Study 2's
`content_signal`: 2*((p_first + p_second)/2) - 1 = p_first + p_second - 1.

SCOPE (D-39). Only self-report and pairwise support this exactly:

  * trade-off   the score averages P(A) *within* each of 9 cost rungs, and 22.7%
                of (item x rung) cells observed only one display order
  * sequential  the score is occupancy over 3 stages, each independently
                randomised; an episode has no single display order

Both are therefore excluded rather than imputed. Adjusted convergence here is a
**single method pair**, not an average over pairs, so it is not comparable in
magnitude to the 3-method matched-subset numbers. Raw and adjusted are computed
on the same two-method basis so the contrast is like-for-like.

This is exploratory, generated by the diagnostics rather than pre-specified.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from . import analysis as A
from . import metrics as M
from .methods.common import displayed_to_semantic

ROOT = Path(__file__).resolve().parents[1]
OUT_TABLE = ROOT / "results" / "tables" / "main_position_adjusted_convergence.csv"
OUT_JSON = ROOT / "results" / "main" / "position_adjusted_convergence.json"

ADJUSTABLE = ["self_report", "pairwise"]
N_PERM = 10_000


def _semantic_value(r: dict) -> float | None:
    """One response in semantic coordinates, on [-1, +1]."""
    sem = displayed_to_semantic(r.get("parsed_choice"), r["display_order"])
    if sem is None:
        return None
    sign = 1.0 if sem == "A" else -1.0
    if r["method"] == "self_report":
        s = r.get("strength_self_report")
        return sign * (float(s) if s is not None else np.nan)
    return sign          # pairwise: +/-1 per response, mean gives 2*P(A)-1


def build_scores(df: pd.DataFrame, items: dict) -> pd.DataFrame:
    """Raw and position-adjusted score per (model, method, item)."""
    ok = df[(df["parse_success"] == True) & (df["framing_variant"] == "neutral")]  # noqa: E712
    ok = ok[~ok["preference_id"].map(lambda p: items[p].sanity_control)]
    ok = ok[ok["method"].isin(ADJUSTABLE)]

    # Median self-reported strength per model, matching the main analysis (D-06).
    med = (ok[ok.method == "self_report"].dropna(subset=["strength_self_report"])
             .groupby("model_key")["strength_self_report"].median().to_dict())

    rows = []
    for (mk, meth, pid), d in ok.groupby(["model_key", "method", "preference_id"]):
        vals = {"ab": [], "ba": []}
        for r in d.to_dict("records"):
            v = _semantic_value(r)
            if v is None:
                continue
            if np.isnan(v):                       # missing self-report strength
                sem = displayed_to_semantic(r["parsed_choice"], r["display_order"])
                v = (1.0 if sem == "A" else -1.0) * med.get(mk, 0.5)
            vals[r["display_order"]].append(v)

        if not vals["ab"] or not vals["ba"]:
            continue                              # cannot adjust without both orders
        allv = vals["ab"] + vals["ba"]
        rows.append({
            "model_key": mk, "method": meth, "preference_id": pid,
            # Raw = the estimator the main analysis uses: mean over all responses.
            "raw": float(np.mean(allv)),
            # Adjusted = mean of the two order-conditioned means (position cancels).
            "adjusted": float((np.mean(vals["ab"]) + np.mean(vals["ba"])) / 2),
            "n_ab": len(vals["ab"]), "n_ba": len(vals["ba"]),
        })
    return pd.DataFrame(rows)


def _pair_stats(x: np.ndarray, y: np.ndarray) -> dict:
    da = M.direction_agreement(x, y)
    return {
        "spearman_rho": M.spearman(x, y)["rho"],
        "direction_agreement": da["agreement"],
        "n_directed": da["n_compared"],
        "sign_flip_rate": M.sign_flip_rate(x, y),
        "mean_abs_disagreement": M.mean_absolute_disagreement(x, y)["mad"],
    }


def _perm(mat: np.ndarray) -> dict:
    def stat(m):
        m = np.asarray(m, dtype=float)
        s = _pair_stats(m[:, 0], m[:, 1])
        return {"spearman_rho": s["spearman_rho"],
                "direction_agreement": s["direction_agreement"]}
    return M.permutation_null(mat, stat, n_perm=N_PERM, seed=20260816)


def run() -> dict:
    exp = A.load_experiment_cfg()
    items = A.load_items()
    df = A.load_raw(exp["main"]["experiment_id"])
    sc = build_scores(df, items)
    OUT_TABLE.parent.mkdir(parents=True, exist_ok=True)
    sc.to_csv(OUT_TABLE, index=False)

    out: dict = {
        "status": "EXPLORATORY - not pre-specified (D-39)",
        "methods": ADJUSTABLE,
        "excluded_methods": {
            "tradeoff": "score averages P(A) within 9 cost rungs; 22.7% of "
                        "(item x rung) cells observed only one display order",
            "sequential": "occupancy over 3 independently randomised stages; an "
                          "episode has no single display order",
        },
        "n_perm": N_PERM,
        "per_model": {},
    }

    print("EXPLORATORY: convergence before vs after removing position")
    print(f"basis: {ADJUSTABLE[0]} x {ADJUSTABLE[1]} (single pair; see D-39)\n")
    hdr = (f"{'model':<22}{'variant':<10}{'rho':>8}{'p_perm':>9}"
           f"{'dir.agr':>9}{'p_perm':>9}{'MAD':>8}{'flips':>7}")
    print(hdr)
    print("-" * len(hdr))

    for mk, d in sc.groupby("model_key"):
        piv_raw = d.pivot(index="preference_id", columns="method", values="raw")
        piv_adj = d.pivot(index="preference_id", columns="method", values="adjusted")
        idx = sorted(set(piv_raw.dropna().index) & set(piv_adj.dropna().index))
        if len(idx) < 4:
            continue
        piv_raw, piv_adj = piv_raw.loc[idx, ADJUSTABLE], piv_adj.loc[idx, ADJUSTABLE]

        res = {}
        for name, piv in (("raw", piv_raw), ("adjusted", piv_adj)):
            m = piv.to_numpy(dtype=float)
            st = _pair_stats(m[:, 0], m[:, 1])
            pn = _perm(m)
            st["p_rho"] = pn["spearman_rho"]["p_empirical"]
            st["p_dir"] = pn["direction_agreement"]["p_empirical"]
            st["null_rho_mean"] = pn["spearman_rho"]["null_mean"]
            res[name] = st
            print(f"{mk:<22}{name:<10}{st['spearman_rho']:>8.3f}{st['p_rho']:>9.4f}"
                  f"{st['direction_agreement']:>9.3f}{st['p_dir']:>9.4f}"
                  f"{st['mean_abs_disagreement']:>8.3f}{st['sign_flip_rate']:>7.2f}")

        res["delta_rho_adjusted_minus_raw"] = (
            res["adjusted"]["spearman_rho"] - res["raw"]["spearman_rho"])
        res["n_items"] = len(idx)
        out["per_model"][mk] = res
        print()

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")
    print("delta rho (adjusted - raw):")
    for mk, r in out["per_model"].items():
        print(f"   {mk:<22}{r['delta_rho_adjusted_minus_raw']:+.3f}")
    print(f"\nwrote -> {OUT_TABLE}")
    return out


if __name__ == "__main__":
    run()
